name: Using different shells for each step

on: [push]

jobs: 
  run-shell-command: 
    runs-on: ubuntu-latest
    steps:
      - name: echo a string
        run: echo "Hello World"
      - name: multiline script
        run: |
          node -v
          npm -v
      - name: python Command
        run: |
          import platform
          print(platform.processor())
        shell: python #indicates what shell in specific to use
  run-windows-commands:
    runs-on: windows-latest
    steps: 
        - name: Directory PowerShell
          run: Get-Location
        - name: Drectory Bash
          run: pwd
          shell: bash #this one needed to be indicated, because we are running a bash command in a windows OS